import React, { useState, useEffect } from 'react';
import { useNavigate, useParams, useLocation } from 'react-router-dom';
import ReactQuill from 'react-quill-new';
import {
  Save,
  Sparkles,
  ChevronLeft,
  Loader2,
  Clock,
  Tags,
  MessageCircle,
  AlertCircle,
  CheckCircle2,
  X,
  BookOpen,
  Calendar,
  Lightbulb
} from 'lucide-react';
import { entryService } from '../services/entryService';
import { geminiService } from '../services/geminiService';
import { categoryService, getCategoryPath } from '../services/categoryService';
import { Category, LearningEntry } from '../types';
import { CategoryTreeSelector } from '../components/categories/CategoryTreeSelector';

interface Toast {
  message: string;
  type: 'success' | 'error';
}

const EntryEditorPage: React.FC = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const location = useLocation();
  const [categories, setCategories] = useState<Category[]>([]);
  const [loading, setLoading] = useState(false);
  const [aiLoading, setAiLoading] = useState(false);
  const [toast, setToast] = useState<Toast | null>(null);
  const [suggestions, setSuggestions] = useState<string[]>([]);
  const [suggLoading, setSuggLoading] = useState(false);

  const [formData, setFormData] = useState<Partial<LearningEntry>>({
    topic: '',
    category: 'General',
    categoryId: undefined,
    categoryPath: [],
    content: '',
    keyTakeaway: '',
    doubts: '',
    timeSpent: { amount: 45, unit: 'minutes' },
    tags: [],
    date: new Date().toISOString().split('T')[0],
    status: 'published',
  });

  const [tagInput, setTagInput] = useState('');

  useEffect(() => {
    const fetchData = async () => {
      try {
        const cats = await categoryService.getCategories();
        setCategories(cats);

        if (id) {
          const entry = await entryService.getEntryById(id);
          if (entry) {
            setFormData(entry);
            return;
          }
        } else {
          // Check for categoryId in query params
          const searchParams = new URLSearchParams(location.search);
          const queryCatId = searchParams.get('category');
          if (queryCatId) {
            const cat = cats.find(c => c._id === queryCatId);
            const path = getCategoryPath(cats, queryCatId);
            if (cat) {
              setFormData(prev => ({ ...prev, categoryId: queryCatId, category: cat.name, categoryPath: path }));
            }
          }
        }
      } catch (err) {
        console.error('Failed to load editor data', err);
      }
    };
    fetchData();
  }, [id, location.search]);

  useEffect(() => {
    if (toast) {
      const timer = setTimeout(() => setToast(null), 3000);
      return () => clearTimeout(timer);
    }
  }, [toast]);

  const handleAiGenerate = async () => {
    const plainText = formData.content?.replace(/<[^>]*>?/gm, '').trim() || '';

    if (plainText.length < 30) {
      setToast({ message: "Content too short for AI analysis (min 30 chars).", type: 'error' });
      return;
    }

    setAiLoading(true);
    try {
      const takeaway = await geminiService.generateKeyTakeaway(plainText);
      setFormData(prev => ({ ...prev, keyTakeaway: takeaway }));
      setToast({ message: "Key takeaway generated by Gemini AI!", type: 'success' });
    } catch (err) {
      setToast({ message: "AI generation failed.", type: 'error' });
    } finally {
      setAiLoading(false);
    }
  };

  const handleGetSuggestions = async () => {
    if (!formData.topic) {
      setToast({ message: "Please enter a topic first.", type: 'error' });
      return;
    }
    setSuggLoading(true);
    try {
      const suggs = await geminiService.getLearningSuggestions(
        formData.topic,
        formData.category || 'General',
        formData.categoryPath
      );
      setSuggestions(suggs);
    } catch (err) {
      setSuggestions(["System Design Patterns", "Concurrency in Depth", "Advanced Testing"]);
    } finally {
      setSuggLoading(false);
    }
  };

  const handleAddTag = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && tagInput.trim()) {
      e.preventDefault();
      if (!formData.tags?.includes(tagInput.trim())) {
        setFormData(prev => ({ ...prev, tags: [...(prev.tags || []), tagInput.trim()] }));
      }
      setTagInput('');
    }
  };

  const removeTag = (tagToRemove: string) => {
    setFormData(prev => ({ ...prev, tags: prev.tags?.filter(t => t !== tagToRemove) }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.topic || !formData.content || !formData.keyTakeaway) {
      setToast({ message: "Please fill in all required fields (Topic, Content, Takeaway).", type: 'error' });
      return;
    }
    setLoading(true);
    try {
      await entryService.saveEntry(formData);
      setToast({ message: id ? "Entry updated successfully!" : "New learning log recorded!", type: 'success' });
      setTimeout(() => {
        navigate('/');
      }, 1200);
    } catch (err) {
      setToast({ message: "Failed to save entry. Please try again.", type: 'error' });
    } finally {
      setLoading(false);
    }
  };

  const quillModules = {
    toolbar: [
      [{ 'header': [1, 2, 3, false] }],
      ['bold', 'italic', 'underline', 'strike'],
      [{ 'list': 'ordered' }, { 'list': 'bullet' }],
      ['code-block', 'blockquote'],
      ['clean']
    ],
  };

  return (
    <div className="max-w-4xl mx-auto pb-16 relative animate-fade-in">
      {/* Toast Notification */}
      {toast && (
        <div
          className={`fixed top-6 right-6 z-[100] flex items-center gap-3 px-5 py-3.5 rounded-2xl shadow-2xl animate-in slide-in-from-right-10 duration-300 border backdrop-blur-md ${
            toast.type === 'success'
              ? 'bg-emerald-600/95 text-white border-emerald-500 shadow-emerald-600/20'
              : 'bg-red-600/95 text-white border-red-500 shadow-red-600/20'
          }`}
        >
          {toast.type === 'success' ? <CheckCircle2 className="w-5 h-5" /> : <AlertCircle className="w-5 h-5" />}
          <p className="font-bold text-sm">{toast.message}</p>
          <button onClick={() => setToast(null)} className="ml-2 opacity-70 hover:opacity-100 transition-opacity">
            <X className="w-4 h-4" />
          </button>
        </div>
      )}

      {/* Header Bar */}
      <div className="flex items-center justify-between mb-6">
        <button
          onClick={() => navigate(-1)}
          className="flex items-center gap-2 px-3 py-2 rounded-xl bg-white/60 dark:bg-slate-800/60 border border-slate-200/60 dark:border-slate-700/60 text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white hover:bg-white dark:hover:bg-slate-800 transition-all text-sm font-semibold shadow-sm"
        >
          <ChevronLeft className="w-4 h-4" />
          <span>Back to Logs</span>
        </button>
        <div className="flex items-center gap-2">
          <span className="text-xs font-bold px-3 py-1.5 rounded-full bg-primary-100 dark:bg-primary-950/80 text-primary-700 dark:text-primary-300 border border-primary-200/50 dark:border-primary-800/50 flex items-center gap-1.5">
            <BookOpen className="w-3.5 h-3.5" />
            <span>{id ? 'Editing Log' : 'New Learning Entry'}</span>
          </span>
        </div>
      </div>

      {/* Main Studio Card */}
      <form onSubmit={handleSubmit} className="bg-white/80 dark:bg-slate-900/80 backdrop-blur-xl border border-white/60 dark:border-white/10 rounded-3xl p-6 md:p-8 shadow-xl space-y-6">
        
        {/* Topic Title & Date */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="md:col-span-2 space-y-1.5">
            <label className="block text-sm font-bold text-slate-700 dark:text-slate-200">
              What did you learn today? *
            </label>
            <input
              type="text"
              required
              placeholder="e.g. Mastered React 19 Action Hooks & Concurrent State..."
              value={formData.topic}
              onChange={(e) => setFormData(prev => ({ ...prev, topic: e.target.value }))}
              className="w-full px-4 py-3 rounded-2xl bg-white dark:bg-slate-850 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white font-bold text-lg placeholder:text-slate-400 dark:placeholder:text-slate-500 focus:outline-none focus:ring-2 focus:ring-primary-500/50 shadow-sm transition-all"
            />
          </div>
          <div className="space-y-1.5">
            <label className="block text-sm font-bold text-slate-700 dark:text-slate-200 flex items-center gap-1.5">
              <Calendar className="w-4 h-4 text-primary-500" />
              <span>Date Recorded *</span>
            </label>
            <input
              type="date"
              required
              value={formData.date}
              onChange={(e) => setFormData(prev => ({ ...prev, date: e.target.value }))}
              className="w-full px-4 py-3 rounded-2xl bg-white dark:bg-slate-850 border border-slate-200 dark:border-slate-700 text-slate-800 dark:text-slate-100 font-semibold focus:outline-none focus:ring-2 focus:ring-primary-500/50 shadow-sm"
            />
          </div>
        </div>

        {/* N-Depth Category Tree Selector */}
        <div className="p-4 rounded-2xl bg-slate-50/70 dark:bg-slate-850/50 border border-slate-200/70 dark:border-slate-800/80">
          <CategoryTreeSelector
            categories={categories}
            selectedCategoryId={formData.categoryId}
            onSelect={(catId, catName, path) => {
              setFormData(prev => ({
                ...prev,
                categoryId: catId,
                category: catName,
                categoryPath: path,
              }));
            }}
            onCategoryCreated={(newCat) => {
              setCategories(prev => [...prev, newCat]);
            }}
          />
        </div>

        {/* Rich Text Studio */}
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <label className="block text-sm font-bold text-slate-700 dark:text-slate-200">
              Detailed Learning Notes & Code Snippets *
            </label>
            <span className="text-xs text-slate-400 dark:text-slate-500">Markdown & syntax highlighted</span>
          </div>
          <div className="bg-white dark:bg-slate-850 rounded-2xl overflow-hidden border border-slate-200 dark:border-slate-700 shadow-inner">
            <ReactQuill
              theme="snow"
              value={formData.content}
              onChange={(val) => setFormData(prev => ({ ...prev, content: val }))}
              modules={quillModules}
              placeholder="Write out your concepts, code examples, diagrams, or architectural takeaways..."
              className="dark:text-slate-100"
            />
          </div>
        </div>

        {/* Key Takeaway + AI Generator */}
        <div className="p-5 rounded-2xl bg-amber-50/50 dark:bg-amber-950/20 border border-amber-200/60 dark:border-amber-800/40 space-y-3">
          <div className="flex items-center justify-between flex-wrap gap-2">
            <label className="block text-sm font-bold text-amber-900 dark:text-amber-200 flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-amber-500 animate-pulse" />
              <span>Core Key Takeaway (TL;DR) *</span>
            </label>
            <button
              type="button"
              onClick={handleAiGenerate}
              disabled={aiLoading}
              className="px-3.5 py-1.5 rounded-xl bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-600 hover:to-orange-600 text-white text-xs font-bold flex items-center gap-1.5 shadow-md shadow-amber-500/20 disabled:opacity-50 transition-all"
            >
              {aiLoading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5" />}
              <span>AI Summarize from Notes</span>
            </button>
          </div>
          <textarea
            required
            rows={2}
            placeholder="In 1-2 sentences, what is the single most important concept or golden rule you learned?"
            value={formData.keyTakeaway}
            onChange={(e) => setFormData(prev => ({ ...prev, keyTakeaway: e.target.value }))}
            className="w-full p-3 rounded-xl bg-white dark:bg-slate-900 border border-amber-200 dark:border-amber-800/60 text-slate-900 dark:text-slate-100 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-amber-500/50 shadow-sm"
          />
        </div>

        {/* Doubts & Time Spent */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="space-y-1.5">
            <label className="block text-sm font-bold text-slate-700 dark:text-slate-200 flex items-center gap-1.5">
              <MessageCircle className="w-4 h-4 text-indigo-500" />
              <span>Open Questions & Doubts (Optional)</span>
            </label>
            <input
              type="text"
              placeholder="What still feels unclear or needs exploration?"
              value={formData.doubts}
              onChange={(e) => setFormData(prev => ({ ...prev, doubts: e.target.value }))}
              className="w-full px-4 py-3 rounded-2xl bg-white dark:bg-slate-850 border border-slate-200 dark:border-slate-700 text-slate-800 dark:text-slate-100 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-primary-500/50 shadow-sm"
            />
          </div>
          <div className="space-y-1.5">
            <label className="block text-sm font-bold text-slate-700 dark:text-slate-200 flex items-center gap-1.5">
              <Clock className="w-4 h-4 text-emerald-500" />
              <span>Time Dedicated</span>
            </label>
            <div className="flex gap-2">
              <input
                type="number"
                min="1"
                required
                value={formData.timeSpent?.amount || 0}
                onChange={(e) => setFormData(prev => ({
                  ...prev,
                  timeSpent: { ...prev.timeSpent!, amount: parseInt(e.target.value) || 0 }
                }))}
                className="w-28 px-4 py-3 rounded-2xl bg-white dark:bg-slate-850 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white font-bold text-center focus:outline-none focus:ring-2 focus:ring-primary-500/50 shadow-sm"
              />
              <select
                value={formData.timeSpent?.unit || 'minutes'}
                onChange={(e: any) => setFormData(prev => ({
                  ...prev,
                  timeSpent: { ...prev.timeSpent!, unit: e.target.value }
                }))}
                className="flex-1 px-4 py-3 rounded-2xl bg-white dark:bg-slate-850 border border-slate-200 dark:border-slate-700 text-slate-800 dark:text-slate-100 font-semibold focus:outline-none focus:ring-2 focus:ring-primary-500/50 shadow-sm cursor-pointer"
              >
                <option value="minutes">Minutes</option>
                <option value="hours">Hours</option>
              </select>
            </div>
          </div>
        </div>

        {/* Tags */}
        <div className="space-y-2">
          <label className="block text-sm font-bold text-slate-700 dark:text-slate-200 flex items-center gap-1.5">
            <Tags className="w-4 h-4 text-blue-500" />
            <span>Tags & Keywords (Press Enter to add)</span>
          </label>
          <div className="p-3 rounded-2xl bg-white dark:bg-slate-850 border border-slate-200 dark:border-slate-700 flex flex-wrap items-center gap-2 shadow-sm min-h-[50px]">
            {formData.tags?.map(tag => (
              <span
                key={tag}
                className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 font-semibold text-xs border border-slate-200 dark:border-slate-700"
              >
                <span>#{tag}</span>
                <button
                  type="button"
                  onClick={() => removeTag(tag)}
                  className="hover:text-red-500 transition-colors"
                >
                  <X className="w-3.5 h-3.5" />
                </button>
              </span>
            ))}
            <input
              type="text"
              placeholder="Add keyword e.g. hooks, dsa, nextjs..."
              value={tagInput}
              onChange={(e) => setTagInput(e.target.value)}
              onKeyDown={handleAddTag}
              className="flex-1 min-w-[150px] bg-transparent text-sm font-medium text-slate-800 dark:text-slate-100 placeholder:text-slate-400 focus:outline-none px-2 py-1"
            />
          </div>
        </div>

        {/* AI Next Topic Suggestions */}
        <div className="p-4 rounded-2xl bg-indigo-50/50 dark:bg-indigo-950/30 border border-indigo-200/60 dark:border-indigo-800/50 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-indigo-500 text-white shadow-md shadow-indigo-500/20">
              <Lightbulb className="w-4 h-4" />
            </div>
            <div>
              <p className="text-sm font-bold text-slate-900 dark:text-white">Curious what to study next?</p>
              <p className="text-xs text-slate-500 dark:text-slate-400">Get Gemini AI recommendations tailored to your active hierarchy path.</p>
            </div>
          </div>
          <button
            type="button"
            onClick={handleGetSuggestions}
            disabled={suggLoading}
            className="px-4 py-2 rounded-xl bg-white dark:bg-slate-850 border border-indigo-200 dark:border-indigo-800 text-indigo-600 dark:text-indigo-400 text-xs font-bold hover:bg-indigo-50 dark:hover:bg-indigo-900/40 transition-all flex items-center gap-1.5 shadow-sm"
          >
            {suggLoading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5" />}
            <span>Get Next Study Topics</span>
          </button>
        </div>

        {suggestions.length > 0 && (
          <div className="p-4 rounded-2xl bg-white dark:bg-slate-850 border border-indigo-200 dark:border-indigo-800 space-y-2 animate-fade-in">
            <p className="text-xs font-extrabold uppercase tracking-wider text-indigo-600 dark:text-indigo-400">Suggested Next Topics:</p>
            <div className="flex flex-wrap gap-2">
              {suggestions.map((sugg, idx) => (
                <button
                  key={idx}
                  type="button"
                  onClick={() => setFormData(prev => ({ ...prev, topic: sugg }))}
                  className="px-3 py-1.5 rounded-xl bg-indigo-50 dark:bg-indigo-950/60 text-indigo-700 dark:text-indigo-300 text-xs font-semibold border border-indigo-200/60 dark:border-indigo-800/60 hover:bg-indigo-100 dark:hover:bg-indigo-900/60 transition-colors"
                >
                  + {sugg}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Submit Actions */}
        <div className="pt-4 border-t border-slate-200/80 dark:border-slate-800 flex items-center justify-end gap-3">
          <button
            type="button"
            onClick={() => navigate(-1)}
            className="px-6 py-3 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-bold text-sm transition-colors"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={loading}
            className="px-8 py-3 rounded-xl bg-gradient-to-r from-primary-600 to-amber-500 hover:from-primary-500 hover:to-amber-400 text-white font-bold text-sm shadow-lg shadow-primary-500/30 hover:shadow-primary-500/40 disabled:opacity-50 transition-all flex items-center gap-2"
          >
            {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
            <span>{id ? 'Save Changes' : 'Publish Learning Log'}</span>
          </button>
        </div>

      </form>
    </div>
  );
};

export default EntryEditorPage;
